//go:build !codegen

// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package advert

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *Spec) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{163}); err != nil {
		return err
	}

	// t.Digest (multihash.Multihash) (slice)
	if len("digest") > 8192 {
		return xerrors.Errorf("Value in field \"digest\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("digest"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("digest")); err != nil {
		return err
	}

	if len(t.Digest) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Digest was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Digest))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Digest); err != nil {
		return err
	}

	// t.Metadata ([]uint8) (slice)
	if len("metadata") > 8192 {
		return xerrors.Errorf("Value in field \"metadata\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("metadata"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("metadata")); err != nil {
		return err
	}

	if len(t.Metadata) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Metadata was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Metadata))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Metadata); err != nil {
		return err
	}

	// t.ContextID ([]uint8) (slice)
	if len("contextID") > 8192 {
		return xerrors.Errorf("Value in field \"contextID\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("contextID"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("contextID")); err != nil {
		return err
	}

	if len(t.ContextID) > 2097152 {
		return xerrors.Errorf("Byte array in field t.ContextID was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.ContextID))); err != nil {
		return err
	}

	if _, err := cw.Write(t.ContextID); err != nil {
		return err
	}

	return nil
}

func (t *Spec) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Spec{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("Spec: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 9)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Digest (multihash.Multihash) (slice)
		case "digest":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Digest: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Digest = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Digest); err != nil {
				return err
			}

			// t.Metadata ([]uint8) (slice)
		case "metadata":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Metadata: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Metadata = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Metadata); err != nil {
				return err
			}

			// t.ContextID ([]uint8) (slice)
		case "contextID":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.ContextID: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.ContextID = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.ContextID); err != nil {
				return err
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
