//go:build !codegen

// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package consolidation

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *Consolidation) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.TrackInvocationBytes ([]uint8) (slice)
	if len("trackInvocation") > 8192 {
		return xerrors.Errorf("Value in field \"trackInvocation\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("trackInvocation"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("trackInvocation")); err != nil {
		return err
	}

	if len(t.TrackInvocationBytes) > 2097152 {
		return xerrors.Errorf("Byte array in field t.TrackInvocationBytes was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.TrackInvocationBytes))); err != nil {
		return err
	}

	if _, err := cw.Write(t.TrackInvocationBytes); err != nil {
		return err
	}

	// t.ConsolidateInvocationCID (cid.Cid) (struct)
	if len("consolidateInvocationCID") > 8192 {
		return xerrors.Errorf("Value in field \"consolidateInvocationCID\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("consolidateInvocationCID"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("consolidateInvocationCID")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.ConsolidateInvocationCID); err != nil {
		return xerrors.Errorf("failed to write cid field t.ConsolidateInvocationCID: %w", err)
	}

	return nil
}

func (t *Consolidation) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Consolidation{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("Consolidation: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 24)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.TrackInvocationBytes ([]uint8) (slice)
		case "trackInvocation":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.TrackInvocationBytes: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.TrackInvocationBytes = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.TrackInvocationBytes); err != nil {
				return err
			}

			// t.ConsolidateInvocationCID (cid.Cid) (struct)
		case "consolidateInvocationCID":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.ConsolidateInvocationCID: %w", err)
				}

				t.ConsolidateInvocationCID = c

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
