// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package aatodo_types

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *PieceLink) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Cid (cid.Cid) (struct)
	if len("cid") > 8192 {
		return fmt.Errorf("string in field \"cid\" was too long")
	}
	if err := jw.WriteString(string("cid")); err != nil {
		return fmt.Errorf("writing string for field \"cid\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Cid); err != nil {
		return fmt.Errorf("writing CID for field t.Cid: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *PieceLink) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = PieceLink{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for PieceLink: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for PieceLink: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for PieceLink: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field PieceLink: string too large")
				}
				return fmt.Errorf("reading string for field PieceLink: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field PieceLink: %w", err)
			}
			switch name {

			// t.Cid (cid.Cid) (struct)
			case "cid":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Cid: %w", err)
					}
					t.Cid = c

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for PieceLink: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field PieceLink: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for PieceLink")
			}
		}
	}

	return nil
}
func (t *Buffer) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.ReverseSortedPieces ([]aatodo_types.PieceLink) (slice)
	if len("reverseSortedPieces") > 8192 {
		return fmt.Errorf("string in field \"reverseSortedPieces\" was too long")
	}
	if err := jw.WriteString(string("reverseSortedPieces")); err != nil {
		return fmt.Errorf("writing string for field \"reverseSortedPieces\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.ReverseSortedPieces) > 8192 {
		return fmt.Errorf("slice value in field t.ReverseSortedPieces was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.ReverseSortedPieces: %w", err)
	}
	for i, v := range t.ReverseSortedPieces {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.ReverseSortedPieces: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.ReverseSortedPieces: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.TotalSize (uint64) (uint64)
	if len("totalSize") > 8192 {
		return fmt.Errorf("string in field \"totalSize\" was too long")
	}
	if err := jw.WriteString(string("totalSize")); err != nil {
		return fmt.Errorf("writing string for field \"totalSize\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.TotalSize)); err != nil {
		return fmt.Errorf("writing uint64 for field t.TotalSize: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Buffer) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Buffer{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Buffer: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Buffer: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Buffer: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Buffer: string too large")
				}
				return fmt.Errorf("reading string for field Buffer: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Buffer: %w", err)
			}
			switch name {

			// t.ReverseSortedPieces ([]aatodo_types.PieceLink) (slice)
			case "reverseSortedPieces":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.ReverseSortedPieces: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.ReverseSortedPieces: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.ReverseSortedPieces: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]PieceLink, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.ReverseSortedPieces = append(t.ReverseSortedPieces, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.ReverseSortedPieces: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.ReverseSortedPieces: slice too large")
							}
						}
					}

				}

				// t.TotalSize (uint64) (uint64)
			case "totalSize":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.TotalSize: %w", err)
					}
					t.TotalSize = uint64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Buffer: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Buffer: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Buffer")
			}
		}
	}

	return nil
}
func (t *ProofData) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Index (uint64) (uint64)
	if len("index") > 8192 {
		return fmt.Errorf("string in field \"index\" was too long")
	}
	if err := jw.WriteString(string("index")); err != nil {
		return fmt.Errorf("writing string for field \"index\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Index)); err != nil {
		return fmt.Errorf("writing uint64 for field t.Index: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Path ([][]uint8) (slice)
	if len("path") > 8192 {
		return fmt.Errorf("string in field \"path\" was too long")
	}
	if err := jw.WriteString(string("path")); err != nil {
		return fmt.Errorf("writing string for field \"path\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Path) > 8192 {
		return fmt.Errorf("slice value in field t.Path was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Path: %w", err)
	}
	for i, v := range t.Path {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Path: %w", err)
			}
		}
		if len(v) > 2097152 {
			return fmt.Errorf("byte array in field v was too long")
		}

		if err := jw.WriteBytes(v); err != nil {
			return fmt.Errorf("writing bytes for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Path: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ProofData) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ProofData{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ProofData: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ProofData: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ProofData: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ProofData: string too large")
				}
				return fmt.Errorf("reading string for field ProofData: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ProofData: %w", err)
			}
			switch name {

			// t.Index (uint64) (uint64)
			case "index":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("reading uint64 for field t.Index: %w", err)
					}
					t.Index = uint64(nval)

				}

				// t.Path ([][]uint8) (slice)
			case "path":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Path: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Path: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Path: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([][]uint8, 1)

							{
								bval, err := jr.ReadBytes(2097152)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading bytes for field item[0]: byte array too large")
									}
									return fmt.Errorf("reading bytes for field item[0]: %w", err)
								}
								if len(bval) > 0 {
									item[0] = []uint8(bval)
								}
							}

							t.Path = append(t.Path, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Path: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Path: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ProofData: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ProofData: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ProofData")
			}
		}
	}

	return nil
}
func (t *AggregatePiece) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.InclusionProof (aatodo_types.ProofData) (struct)
	if len("inclusionProof") > 8192 {
		return fmt.Errorf("string in field \"inclusionProof\" was too long")
	}
	if err := jw.WriteString(string("inclusionProof")); err != nil {
		return fmt.Errorf("writing string for field \"inclusionProof\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.InclusionProof.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.InclusionProof: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Link (aatodo_types.PieceLink) (struct)
	if len("link") > 8192 {
		return fmt.Errorf("string in field \"link\" was too long")
	}
	if err := jw.WriteString(string("link")); err != nil {
		return fmt.Errorf("writing string for field \"link\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Link.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Link: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *AggregatePiece) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = AggregatePiece{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for AggregatePiece: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for AggregatePiece: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for AggregatePiece: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field AggregatePiece: string too large")
				}
				return fmt.Errorf("reading string for field AggregatePiece: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field AggregatePiece: %w", err)
			}
			switch name {

			// t.InclusionProof (aatodo_types.ProofData) (struct)
			case "inclusionProof":

				if err := t.InclusionProof.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.InclusionProof: %w", err)
				}

				// t.Link (aatodo_types.PieceLink) (struct)
			case "link":

				if err := t.Link.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Link: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for AggregatePiece: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field AggregatePiece: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for AggregatePiece")
			}
		}
	}

	return nil
}
func (t *Aggregate) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Pieces ([]aatodo_types.AggregatePiece) (slice)
	if len("pieces") > 8192 {
		return fmt.Errorf("string in field \"pieces\" was too long")
	}
	if err := jw.WriteString(string("pieces")); err != nil {
		return fmt.Errorf("writing string for field \"pieces\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Pieces) > 8192 {
		return fmt.Errorf("slice value in field t.Pieces was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Pieces: %w", err)
	}
	for i, v := range t.Pieces {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Pieces: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Pieces: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Root (aatodo_types.PieceLink) (struct)
	if len("root") > 8192 {
		return fmt.Errorf("string in field \"root\" was too long")
	}
	if err := jw.WriteString(string("root")); err != nil {
		return fmt.Errorf("writing string for field \"root\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Root.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Root: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Aggregate) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Aggregate{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Aggregate: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Aggregate: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Aggregate: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Aggregate: string too large")
				}
				return fmt.Errorf("reading string for field Aggregate: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Aggregate: %w", err)
			}
			switch name {

			// t.Pieces ([]aatodo_types.AggregatePiece) (slice)
			case "pieces":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Pieces: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Pieces: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Pieces: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]AggregatePiece, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Pieces = append(t.Pieces, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Pieces: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Pieces: slice too large")
							}
						}
					}

				}

				// t.Root (aatodo_types.PieceLink) (struct)
			case "root":

				if err := t.Root.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Root: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Aggregate: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Aggregate: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Aggregate")
			}
		}
	}

	return nil
}
func (t *Aggregation) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Roots ([]cid.Cid) (slice)
	if len("roots") > 8192 {
		return fmt.Errorf("string in field \"roots\" was too long")
	}
	if err := jw.WriteString(string("roots")); err != nil {
		return fmt.Errorf("writing string for field \"roots\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Roots) > 8192 {
		return fmt.Errorf("slice value in field t.Roots was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Roots: %w", err)
	}
	for i, v := range t.Roots {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Roots: %w", err)
			}
		}

		if err := jw.WriteCid(v); err != nil {
			return fmt.Errorf("writing CID for field v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Roots: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Aggregation) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Aggregation{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Aggregation: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Aggregation: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Aggregation: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Aggregation: string too large")
				}
				return fmt.Errorf("reading string for field Aggregation: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Aggregation: %w", err)
			}
			switch name {

			// t.Roots ([]cid.Cid) (slice)
			case "roots":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Roots: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Roots: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Roots: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]cid.Cid, 1)
							{

								c, err := jr.ReadCid()
								if err != nil {
									return fmt.Errorf("reading CID for field item[0]: %w", err)
								}
								item[0] = c

							}
							t.Roots = append(t.Roots, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Roots: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Roots: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Aggregation: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Aggregation: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Aggregation")
			}
		}
	}

	return nil
}
func (t *Blob) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Digest ([]uint8) (slice)
	if len("digest") > 8192 {
		return fmt.Errorf("string in field \"digest\" was too long")
	}
	if err := jw.WriteString(string("digest")); err != nil {
		return fmt.Errorf("writing string for field \"digest\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Digest) > 2097152 {
		return fmt.Errorf("byte array in field t.Digest was too long")
	}

	if err := jw.WriteBytes(t.Digest); err != nil {
		return fmt.Errorf("writing bytes for field t.Digest: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Blob) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Blob{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Blob: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Blob: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Blob: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Blob: string too large")
				}
				return fmt.Errorf("reading string for field Blob: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Blob: %w", err)
			}
			switch name {

			// t.Digest ([]uint8) (slice)
			case "digest":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Digest: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Digest: %w", err)
					}
					if len(bval) > 0 {
						t.Digest = []uint8(bval)
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Blob: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Blob: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Blob")
			}
		}
	}

	return nil
}
