//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package allocation

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	ucan "github.com/fil-forge/ucantone/ucan"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *Allocation) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := false

	// t.Blob (blob.Blob) (struct)
	if len("blob") > 8192 {
		return fmt.Errorf("string in field \"blob\" was too long")
	}
	if err := jw.WriteString(string("blob")); err != nil {
		return fmt.Errorf("writing string for field \"blob\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Blob.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Blob: %w", err)
	}
	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cause (cid.Cid) (struct)
	if len("cause") > 8192 {
		return fmt.Errorf("string in field \"cause\" was too long")
	}
	if err := jw.WriteString(string("cause")); err != nil {
		return fmt.Errorf("writing string for field \"cause\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteCid(t.Cause); err != nil {
		return fmt.Errorf("writing CID for field t.Cause: %w", err)
	}

	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Expires (ucan.UnixTimestamp) (int64)
	if len("expired") > 8192 {
		return fmt.Errorf("string in field \"expired\" was too long")
	}
	if err := jw.WriteString(string("expired")); err != nil {
		return fmt.Errorf("writing string for field \"expired\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Expires)); err != nil {
		return fmt.Errorf("writing int64 for field t.Expires: %w", err)
	}

	written = true
	if written {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Space (did.DID) (struct)
	if len("space") > 8192 {
		return fmt.Errorf("string in field \"space\" was too long")
	}
	if err := jw.WriteString(string("space")); err != nil {
		return fmt.Errorf("writing string for field \"space\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Space.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Space: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Allocation) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Allocation{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Allocation: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Allocation: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Allocation: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Allocation: string too large")
				}
				return fmt.Errorf("reading string for field Allocation: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Allocation: %w", err)
			}
			switch name {

			// t.Blob (blob.Blob) (struct)
			case "blob":

				if err := t.Blob.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Blob: %w", err)
				}

				// t.Cause (cid.Cid) (struct)
			case "cause":
				{

					c, err := jr.ReadCid()
					if err != nil {
						return fmt.Errorf("reading CID for field t.Cause: %w", err)
					}
					t.Cause = c

				}

				// t.Expires (ucan.UnixTimestamp) (int64)
			case "expired":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Expires: %w", err)
					}
					t.Expires = ucan.UnixTimestamp(nval)

				}

				// t.Space (did.DID) (struct)
			case "space":

				if err := t.Space.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Space: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Allocation: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Allocation: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Allocation")
			}
		}
	}

	return nil
}
