//go:build !codegen

// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.
//
// Hand-written copy of what cbor-gen would emit for Aggregation —
// the local piri-signing-service checkout transitively imported by
// the manager package breaks the codegen build, so `go run -tags
// codegen .` in manager/gen can't import the manager package today.
// When that chain compiles cleanly this can be regenerated; the
// shape mirrors types.ManagerJob (same {Roots []cid.Cid} structure)
// so the encoding is bit-for-bit identical.

package manager

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *Aggregation) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{161}); err != nil {
		return err
	}

	// t.Roots ([]cid.Cid) (slice)
	if len("roots") > 8192 {
		return xerrors.Errorf("Value in field \"roots\" was too long")
	}
	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("roots"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("roots")); err != nil {
		return err
	}

	if len(t.Roots) > 8192 {
		return xerrors.Errorf("Slice value in field t.Roots was too long")
	}
	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Roots))); err != nil {
		return err
	}
	for _, v := range t.Roots {
		if err := cbg.WriteCid(cw, v); err != nil {
			return xerrors.Errorf("failed to write cid field v: %w", err)
		}
	}
	return nil
}

func (t *Aggregation) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Aggregation{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}
	if extra > cbg.MaxLength {
		return fmt.Errorf("Aggregation: map struct too large (%d)", extra)
	}

	n := extra
	nameBuf := make([]byte, 5)

	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}
		if !ok {
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		case "roots":
			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if extra > 8192 {
				return fmt.Errorf("t.Roots: array too large (%d)", extra)
			}
			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}
			if extra > 0 {
				t.Roots = make([]cid.Cid, extra)
			}
			for i := 0; i < int(extra); i++ {
				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.Roots[i]: %w", err)
				}
				t.Roots[i] = c
			}

		default:
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
