// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package acceptance

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *Acceptance) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 5

	if t.PDPAccept == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Blob (acceptance.Blob) (struct)
	if len("blob") > 8192 {
		return xerrors.Errorf("Value in field \"blob\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("blob"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("blob")); err != nil {
		return err
	}

	if err := t.Blob.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Cause (cid.Cid) (struct)
	if len("cause") > 8192 {
		return xerrors.Errorf("Value in field \"cause\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("cause"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("cause")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.Cause); err != nil {
		return xerrors.Errorf("failed to write cid field t.Cause: %w", err)
	}

	// t.Space (did.DID) (struct)
	if len("space") > 8192 {
		return xerrors.Errorf("Value in field \"space\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("space"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("space")); err != nil {
		return err
	}

	if err := t.Space.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.PDPAccept (acceptance.Promise) (struct)
	if t.PDPAccept != nil {

		if len("pdpAccept") > 8192 {
			return xerrors.Errorf("Value in field \"pdpAccept\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("pdpAccept"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("pdpAccept")); err != nil {
			return err
		}

		if err := t.PDPAccept.MarshalCBOR(cw); err != nil {
			return err
		}
	}

	// t.ExecutedAt (uint64) (uint64)
	if len("executedAt") > 8192 {
		return xerrors.Errorf("Value in field \"executedAt\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("executedAt"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("executedAt")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.ExecutedAt)); err != nil {
		return err
	}

	return nil
}

func (t *Acceptance) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Acceptance{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("Acceptance: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 10)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Blob (acceptance.Blob) (struct)
		case "blob":

			{

				if err := t.Blob.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Blob: %w", err)
				}

			}
			// t.Cause (cid.Cid) (struct)
		case "cause":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.Cause: %w", err)
				}

				t.Cause = c

			}
			// t.Space (did.DID) (struct)
		case "space":

			{

				if err := t.Space.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Space: %w", err)
				}

			}
			// t.PDPAccept (acceptance.Promise) (struct)
		case "pdpAccept":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					t.PDPAccept = new(Promise)
					if err := t.PDPAccept.UnmarshalCBOR(cr); err != nil {
						return xerrors.Errorf("unmarshaling t.PDPAccept pointer: %w", err)
					}
				}

			}
			// t.ExecutedAt (uint64) (uint64)
		case "executedAt":

			{

				maj, extra, err = cr.ReadHeader()
				if err != nil {
					return err
				}
				if maj != cbg.MajUnsignedInt {
					return fmt.Errorf("wrong type for uint64 field")
				}
				t.ExecutedAt = uint64(extra)

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *Blob) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Size (uint64) (uint64)
	if len("size") > 8192 {
		return xerrors.Errorf("Value in field \"size\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("size"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("size")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Size)); err != nil {
		return err
	}

	// t.Digest (multihash.Multihash) (slice)
	if len("digest") > 8192 {
		return xerrors.Errorf("Value in field \"digest\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("digest"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("digest")); err != nil {
		return err
	}

	if len(t.Digest) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Digest was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Digest))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Digest); err != nil {
		return err
	}

	return nil
}

func (t *Blob) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Blob{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("Blob: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 6)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Size (uint64) (uint64)
		case "size":

			{

				maj, extra, err = cr.ReadHeader()
				if err != nil {
					return err
				}
				if maj != cbg.MajUnsignedInt {
					return fmt.Errorf("wrong type for uint64 field")
				}
				t.Size = uint64(extra)

			}
			// t.Digest (multihash.Multihash) (slice)
		case "digest":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Digest: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Digest = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Digest); err != nil {
				return err
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *Promise) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{161}); err != nil {
		return err
	}

	// t.UcanAwait (acceptance.Await) (struct)
	if len("ucan/await") > 8192 {
		return xerrors.Errorf("Value in field \"ucan/await\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("ucan/await"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("ucan/await")); err != nil {
		return err
	}

	if err := t.UcanAwait.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *Promise) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Promise{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("Promise: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 10)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.UcanAwait (acceptance.Await) (struct)
		case "ucan/await":

			{

				if err := t.UcanAwait.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.UcanAwait: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *Await) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Link (cid.Cid) (struct)
	if len("link") > 8192 {
		return xerrors.Errorf("Value in field \"link\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("link"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("link")); err != nil {
		return err
	}

	if err := cbg.WriteCid(cw, t.Link); err != nil {
		return xerrors.Errorf("failed to write cid field t.Link: %w", err)
	}

	// t.Selector (string) (string)
	if len("selector") > 8192 {
		return xerrors.Errorf("Value in field \"selector\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("selector"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("selector")); err != nil {
		return err
	}

	if len(t.Selector) > 8192 {
		return xerrors.Errorf("Value in field t.Selector was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Selector))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Selector)); err != nil {
		return err
	}
	return nil
}

func (t *Await) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Await{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("Await: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Link (cid.Cid) (struct)
		case "link":

			{

				c, err := cbg.ReadCid(cr)
				if err != nil {
					return xerrors.Errorf("failed to read cid field t.Link: %w", err)
				}

				t.Link = c

			}
			// t.Selector (string) (string)
		case "selector":

			{
				sval, err := cbg.ReadStringWithMax(cr, 8192)
				if err != nil {
					return err
				}

				t.Selector = string(sval)
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
